
<div class="row">
	<div class="col-md-8">
		<div class="jumbotron">
			<h1>
				<?= sprintf($this->translate('%sMy Weather Station%s'), '<span class="zf-green">', '</span>'); ?>
			</h1>
			<p><?php echo $this->translate('Welcome to my weather station!'); ?></p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-green" style="background-color: #eee">
			<div class="panel-body">
				<a href="#" class="aw-widget-legal"></a>
				<div id="awcc1499536313942" class="aw-widget-current"  data-locationkey="" data-unit="c" data-language="el" data-useip="true" data-uid="awcc1499536313942"></div>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript" src="https://oap.accuweather.com/launch.js"></script>